<a href="https://colab.research.google.com/github/joshuaghannan/ECEC247_Project/blob/jgh_tests/PyTorch_Experiments.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
########################################################

# If running with Google Colab

from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [15]:
########################################################

# If running with Google Colab
# Create a folder "C247" and then store the project datasets within that folder
# Check that your datasets are setup correctly

!ls "/content/gdrive/My Drive/C247" # File path

EEG_loading.ipynb	PyTorch_Experiments.ipynb  y_test.npy
person_test.npy		X_test.npy		   y_train_valid.npy
person_train_valid.npy	X_train_valid.npy


In [0]:
import numpy as np

### Load the Datasets

In [0]:
# X_test = np.load("X_test.npy")
# y_test = np.load("y_test.npy")
# person_train_valid = np.load("person_train_valid.npy")
# X_train_valid = np.load("X_train_valid.npy")
# y_train_valid = np.load("y_train_valid.npy")
# person_test = np.load("person_test.npy")

# Change if your directory is different
dataset_path = "/content/gdrive/My Drive/C247/" 

X_test = np.load(dataset_path + "X_test.npy")
y_test = np.load(dataset_path + "y_test.npy")
person_train_valid = np.load(dataset_path + "person_train_valid.npy")
X_train_valid = np.load(dataset_path + "X_train_valid.npy")
y_train_valid = np.load(dataset_path + "y_train_valid.npy")
person_test = np.load(dataset_path + "person_test.npy")

### Shape of data

In [18]:
print ('Training/Valid data shape: {}'.format(X_train_valid.shape))
print ('Test data shape: {}'.format(X_test.shape))
print ('Training/Valid target shape: {}'.format(y_train_valid.shape))
print ('Test target shape: {}'.format(y_test.shape))
print ('Person train/valid shape: {}'.format(person_train_valid.shape))
print ('Person test shape: {}'.format(person_test.shape))


Training/Valid data shape: (2115, 22, 1000)
Test data shape: (443, 22, 1000)
Training/Valid target shape: (2115,)
Test target shape: (443,)
Person train/valid shape: (2115, 1)
Person test shape: (443, 1)


### Setting Up PyTorch

In [0]:
from __future__ import print_function
import torch


In [20]:
x = torch.empty(5, 3)
print(x)

tensor([[4.4652e-37, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [4.2886e-08, 6.5640e-07, 2.7626e-06],
        [5.4718e+22, 2.1236e+20, 6.6754e-07],
        [2.1857e-04, 2.5963e+20, 7.5649e+28]])


In [21]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7142, 0.5740, 0.4113],
        [0.0204, 0.5760, 0.0524],
        [0.0850, 0.2658, 0.6003],
        [0.4570, 0.4046, 0.6028],
        [0.2066, 0.1826, 0.6996]])


In [22]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [23]:
x = torch.tensor([5.5, 3])
print(x)
print(x.size())

tensor([5.5000, 3.0000])
torch.Size([2])


In [24]:
y = torch.rand(1, 2)
print(x+y)

tensor([[5.8433, 3.9800]])


In [25]:
result = torch.empty(1,2)
torch.add(x, y, out=result)
print(result)


tensor([[5.8433, 3.9800]])


In [26]:
y.add_(x)
print(y)

tensor([[5.8433, 3.9800]])


In [27]:
q = torch.rand(5,3)
print(q)
print(q[1][:])

tensor([[0.6983, 0.1128, 0.8698],
        [0.7465, 0.6457, 0.5868],
        [0.8044, 0.8688, 0.2930],
        [0.3126, 0.2733, 0.5882],
        [0.2644, 0.4469, 0.2426]])
tensor([0.7465, 0.6457, 0.5868])


In [28]:
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [29]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([6.5000, 4.0000], device='cuda:0')
tensor([6.5000, 4.0000], dtype=torch.float64)
